### ISSUE TITLE
MiniBeacon_000056 card based Beacon issue

### ISSUE THREAD

**Issue by dj-4war** [smartbeacon/smartbeacon-android-sdk#7]
I have a beacon purchased from one of the Chines store with the model MiniBeacon_00056 Major 10001, Minor 19641. Beacon provider has given this SDK.
I integrated  library with the my app when I run the app on 4.3.2 device[HTC M8], I am not able to see any call back for SBLocationManagerListeners, but
I see logs with Bluetooth Adapter like below, which says it is detecting the MAC ID using BluetoothAdapter but bot call backs. Logs as mentioned below.

01-17 18:59:58.483 19628-19640/? D/BluetoothDevice: getService() entry
01-17 18:59:58.983 19628-19639/? D/BluetoothAdapter: onScanResult() - Device=FA:3D:57:F7:2C:80 RSSI=-76
01-17 18:59:58.993 19628-19639/? D/BluetoothDevice: getService() entry
01-17 18:59:59.383 19628-19640/? D/BluetoothAdapter: onScanResult() - Device=C9:12:14:0C:41:E7 RSSI=-81
01-17 18:59:59.393 19628-19640/? D/BluetoothDevice: getService() entry
01-17 18:59:59.483 19628-19639/? D/BluetoothAdapter: onScanResult() - Device=FA:3D:57:F7:2C:80 RSSI=-72
01-17 18:59:59.483 19628-19639/? D/BluetoothDevice: getService() entry
01-17 18:59:59.533 19628-19628/? D/BluetoothAdapter: stopLeScan()
01-17 19:00:02.583 19628-19628/? D/BluetoothAdapter: startLeScan(): null

When I run the same app on Moto X Pure which has a 6.0, throwing security exception saying add course location in manifest, though I have added all the permissions.

 
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true" />

```
<!-- Network permissions -->
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.INTERNET" />
```

An I just see below exception not even Bluetooth adapter. 
Exception : 

01-17 19:04:38.500 20201-20201/com.guesberi.sample D/BluetoothAdapter: stopLeScan()
01-17 19:04:41.503 20201-20201/com.guesberi.sample D/BluetoothAdapter: startLeScan(): null
01-17 19:04:41.514 20201-20201/com.guesberi.sample D/BluetoothAdapter: STATE_ON
01-17 19:04:41.520 20201-20212/com.guesberi.sample D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
01-17 19:04:41.539 20201-20212/com.guesberi.sample W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                             java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
                                                                 at android.os.Parcel.readException(Parcel.java:1599)
                                                                 at android.os.Parcel.readException(Parcel.java:1552)
                                                                 at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:772)
                                                                 at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:324)
                                                                 at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
                                                                 at android.os.Binder.execTransact(Binder.java:453)
01-17 19:04:46.523 20201-20201/com.guesberi.sample D/BluetoothAdapter: stopLeScan()
01-17 19:04:46.528 20201-20201/com.guesberi.sample D/BluetoothAdapter: STATE_ON
01-17 19:04:49.548 20201-20201/com.guesberi.sample D/BluetoothAdapter: startLeScan(): null
01-17 19:04:49.550 20201-20201/com.guesberi.sample D/BluetoothAdapter: STATE_ON
01-17 19:04:49.552 20201-20213/com.guesberi.sample D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
01-17 19:04:49.555 20201-20213/com.guesberi.sample W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                             java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
                                                                 at android.os.Parcel.readException(Parcel.java:1599)
                                                                 at android.os.Parcel.readException(Parcel.java:1552)
                                                                 at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:772)
                                                                 at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:324)
                                                                 at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
                                                                 at android.os.Binder.execTransact(Binder.java:453)
01-17 19:04:54.556 20201-20201/com.xyz.sample D/BluetoothAdapter: stopLeScan()
01-17 19:04:54.573 20201-20201/com.xyz.sample D/BluetoothAdapter: STATE_ON
01-17 19:04:57.584 20201-20201/com.xyz.sample D/BluetoothAdapter: startLeScan(): null
01-17 19:04:57.587 20201-20201/com.xyz.sample D/BluetoothAdapter: STATE_ON
01-17 19:04:57.593 20201-20212/com.xyz.sample D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5

Sooner response is appreciated.

**Comment by dj-4war** [comment]
Below is the beacon that we have purchased,

http://szsanwo.en.alibaba.com/product/60401366235-801749367/2016_new_Credit_card_type_waterproof_sensor_customized_bluetooth_beacon.html
